version: '3.8'

services:
  movieapp-db:
    build:
      context: ./database  # Wskazuje katalog, w którym znajduje się Dockerfile i init.sql
      dockerfile: Dockerfile
    container_name: movieapp-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: MovieApp
      MYSQL_USER: movie_user
      MYSQL_PASSWORD: movie_password

    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    driver: local
